# Use the official Node.js image as a base
FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY src/ ./src/

# Expose the port the app runs on
EXPOSE 9982

# Command to run the application
CMD ["node", "src/index-google-analytics.js"]